import React, { ChangeEvent } from 'react';
import { Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import type { RepoAnalysis } from '@/types';

interface DataImportProps {
  onDataLoad: (data: RepoAnalysis) => void;
}

export function DataImport({ onDataLoad }: DataImportProps) {
  const handleFileUpload = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const json = JSON.parse(e.target?.result as string);
        onDataLoad(json);
      } catch (error) {
        alert('Error parsing JSON file. Please ensure it\'s a valid repo-scanner output.');
        console.error('JSON parse error:', error);
      }
    };
    reader.readAsText(file);
  };

  return (
    <Card>
      <CardContent className="flex flex-col items-center justify-center p-12">
        <Upload className="w-12 h-12 text-muted-foreground mb-4" />
        <h2 className="text-xl font-semibold mb-2">Import Analysis Data</h2>
        <p className="text-muted-foreground text-center mb-6">
          Upload a JSON file generated by repo-scanner to visualize the analysis
        </p>
        <Button asChild>
          <label htmlFor="file-upload" className="cursor-pointer">
            Choose JSON File
            <input
              id="file-upload"
              type="file"
              accept=".json"
              onChange={handleFileUpload}
              className="hidden"
            />
          </label>
        </Button>
      </CardContent>
    </Card>
  );
}